# Generated by Django 5.0.9 on 2025-01-09 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de facture"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(verbose_name="Adresse de facturation"),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="TVA"
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Date d'échéance")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Annulée le"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Raison d'annulation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "unit_price_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire HT"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux de TVA (%)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Poids du produit",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="factures.invoice",
                    ),
                ),
            ],
        ),
    ]
