# Generated by Django 5.0.9 on 2025-01-09 14:32

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("taxes", "0002_taxmatrice_taxproduct_taxuser_delete_tax_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introduction de la page des produits"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("paginated_product_list", 11),
                            ("limited_product_list", 14),
                            ("paginated_product_category_list", 16),
                            ("limited_product_category_list", 19),
                            ("paginated_blog_list", 23),
                            ("limited_blog_list", 26),
                            ("paginated_blog_category_list", 28),
                            ("limited_blog_category_list", 31),
                            ("single_column", 51),
                            ("double_column", 55),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("normal", "Espacement normal"),
                                        ("large", "Grand espacement"),
                                    ],
                                    "help_text": "Choisir l'espacement entre les éléments",
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("primary-light", "Primary Light"),
                                        ("primary-dark", "Primary Dark"),
                                        ("secondary", "Secondary"),
                                        ("secondary-light", "Secondary Light"),
                                        ("secondary-dark", "Secondary Dark"),
                                        ("accent", "Accent"),
                                        ("accent-light", "Accent Light"),
                                        ("accent-dark", "Accent Dark"),
                                        ("dark", "Dark"),
                                        ("light", "Light"),
                                    ],
                                    "help_text": "Choisir la couleur du texte",
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centre"),
                                        ("right", "Droite"),
                                    ],
                                    "help_text": "Choisir l'alignement du texte",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du titre",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ],
                                    "help_text": "Choisir le niveau du titre",
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {
                                    "help_text": "Titre facultatif pour cette section",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du paragraphe",
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {
                                    "help_text": "Texte facultatif pour cette section",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 6,
                                    "help_text": "Nombre de produits par page",
                                },
                            ),
                            9: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["product.ProductCategory"]},
                            ),
                            10: (
                                "wagtail.blocks.ListBlock",
                                (9,),
                                {
                                    "help_text": "Choisissez les catégories pour filtrer les produits",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 8),
                                        ("categories", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de produits à afficher",
                                },
                            ),
                            13: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les produits vedettes",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 12),
                                        ("featured_only", 13),
                                        ("categories", 10),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 6,
                                    "help_text": "Nombre de catégories de produits par page",
                                },
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 5), ("paragraph", 7), ("limit", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de catégories de produits à afficher",
                                },
                            ),
                            18: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les catégories vedettes",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 17),
                                        ("featured_only", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre d'articles de blog par page",
                                },
                            ),
                            21: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["blog.BlogCategoryPage"]},
                            ),
                            22: (
                                "wagtail.blocks.ListBlock",
                                (21,),
                                {
                                    "help_text": "Choisissez les catégories pour filtrer les articles",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 20),
                                        ("categories", 22),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre d'articles de blog à afficher",
                                },
                            ),
                            25: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les articles en vedette",
                                    "required": False,
                                },
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 24),
                                        ("featured_only", 25),
                                        ("categories", 22),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de catégories de blog par page",
                                },
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 5), ("paragraph", 7), ("limit", 27)]],
                                {},
                            ),
                            29: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de catégories de blog à afficher",
                                },
                            ),
                            30: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les catégories en vedette",
                                    "required": False,
                                },
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 29),
                                        ("featured_only", 30),
                                    ]
                                ],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {},
                            ),
                            34: ("streams.blocks.ButtonGroupBlock", (), {}),
                            35: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choisir une image", "required": True},
                            ),
                            36: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            37: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Petite"),
                                        ("medium", "Moyenne"),
                                        ("large", "Grande"),
                                    ],
                                    "help_text": "Choisir la taille de l'image",
                                },
                            ),
                            38: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("lazy", "Lazy (différé)"),
                                        ("eager", "Eager (immédiat)"),
                                    ],
                                    "help_text": "Choisir la méthode de chargement de l'image",
                                },
                            ),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("alignment", 2),
                                        ("image", 35),
                                        ("alt_text", 36),
                                        ("size", 37),
                                        ("loading", 38),
                                    ]
                                ],
                                {},
                            ),
                            40: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 35), ("alt_text", 40)]],
                                {},
                            ),
                            42: ("wagtail.blocks.ListBlock", (41,), {}),
                            43: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Disposition par défaut"),
                                        ("carousel", "Carrousel"),
                                        ("slider", "Slider"),
                                        ("photography", "Photography"),
                                    ],
                                    "help_text": "Choisir le style de galerie",
                                },
                            ),
                            44: (
                                "wagtail.blocks.StructBlock",
                                [[("images", 42), ("style", 43)]],
                                {},
                            ),
                            45: ("wagtail.blocks.RichTextBlock", (), {}),
                            46: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document", "required": False},
                            ),
                            47: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Ajouter un média externe (vidéo, audio, etc.)"
                                },
                            ),
                            48: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            49: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Item de liste"},
                            ),
                            50: ("wagtail.blocks.ListBlock", (49,), {}),
                            51: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 32),
                                        ("paragraph", 33),
                                        ("buttons", 34),
                                        ("image", 39),
                                        ("Gallery", 44),
                                        ("richtext", 45),
                                        ("document", 46),
                                        ("embed", 47),
                                        ("quote", 48),
                                        ("list", 50),
                                    ]
                                ],
                                {},
                            ),
                            52: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Ajouter un texte ou une description avant les colonnes",
                                    "required": False,
                                },
                            ),
                            53: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 32),
                                        ("paragraph", 33),
                                        ("buttons", 34),
                                        ("image", 39),
                                        ("gallery", 44),
                                        ("richtext", 45),
                                        ("document", 46),
                                        ("embed", 47),
                                        ("quote", 48),
                                        ("list", 50),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne gauche",
                                    "required": False,
                                },
                            ),
                            54: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 32),
                                        ("paragraph", 33),
                                        ("buttons", 34),
                                        ("image", 39),
                                        ("gallery", 44),
                                        ("richtext", 45),
                                        ("document", 46),
                                        ("embed", 47),
                                        ("quote", 48),
                                        ("list", 50),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne droite",
                                    "required": False,
                                },
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("rich_text", 52),
                                        ("left_column", 53),
                                        ("right_column", 54),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Boutique",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de la variante (par ex. Taille, Couleur)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("summary", wagtail.fields.RichTextField(blank=True)),
                ("content", wagtail.fields.RichTextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("single_column", 25), ("double_column", 29)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("normal", "Espacement normal"),
                                        ("large", "Grand espacement"),
                                    ],
                                    "help_text": "Choisir l'espacement entre les éléments",
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("primary-light", "Primary Light"),
                                        ("primary-dark", "Primary Dark"),
                                        ("secondary", "Secondary"),
                                        ("secondary-light", "Secondary Light"),
                                        ("secondary-dark", "Secondary Dark"),
                                        ("accent", "Accent"),
                                        ("accent-light", "Accent Light"),
                                        ("accent-dark", "Accent Dark"),
                                        ("dark", "Dark"),
                                        ("light", "Light"),
                                    ],
                                    "help_text": "Choisir la couleur du texte",
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centre"),
                                        ("right", "Droite"),
                                    ],
                                    "help_text": "Choisir l'alignement du texte",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du titre",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ],
                                    "help_text": "Choisir le niveau du titre",
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du paragraphe",
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: ("streams.blocks.ButtonGroupBlock", (), {}),
                            9: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choisir une image", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Petite"),
                                        ("medium", "Moyenne"),
                                        ("large", "Grande"),
                                    ],
                                    "help_text": "Choisir la taille de l'image",
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("lazy", "Lazy (différé)"),
                                        ("eager", "Eager (immédiat)"),
                                    ],
                                    "help_text": "Choisir la méthode de chargement de l'image",
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("alignment", 2),
                                        ("image", 9),
                                        ("alt_text", 10),
                                        ("size", 11),
                                        ("loading", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 9), ("alt_text", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Disposition par défaut"),
                                        ("carousel", "Carrousel"),
                                        ("slider", "Slider"),
                                        ("photography", "Photography"),
                                    ],
                                    "help_text": "Choisir le style de galerie",
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("images", 16), ("style", 17)]],
                                {},
                            ),
                            19: ("wagtail.blocks.RichTextBlock", (), {}),
                            20: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document", "required": False},
                            ),
                            21: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Ajouter un média externe (vidéo, audio, etc.)"
                                },
                            ),
                            22: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Item de liste"},
                            ),
                            24: ("wagtail.blocks.ListBlock", (23,), {}),
                            25: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("Gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {},
                            ),
                            26: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Ajouter un texte ou une description avant les colonnes",
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne gauche",
                                    "required": False,
                                },
                            ),
                            28: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne droite",
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("rich_text", 26),
                                        ("left_column", 27),
                                        ("right_column", 28),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("summary", wagtail.fields.RichTextField(blank=True)),
                ("content", wagtail.fields.RichTextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_included", models.BooleanField(default=False)),
                ("sku", models.CharField(blank=True, max_length=255)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "variants",
                    wagtail.fields.StreamField(
                        [("variant", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("product.ProductVariant",),
                                {"required": True},
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("variant", 0)]], {}),
                        },
                        null=True,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("single_column", 25), ("double_column", 29)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("normal", "Espacement normal"),
                                        ("large", "Grand espacement"),
                                    ],
                                    "help_text": "Choisir l'espacement entre les éléments",
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("primary-light", "Primary Light"),
                                        ("primary-dark", "Primary Dark"),
                                        ("secondary", "Secondary"),
                                        ("secondary-light", "Secondary Light"),
                                        ("secondary-dark", "Secondary Dark"),
                                        ("accent", "Accent"),
                                        ("accent-light", "Accent Light"),
                                        ("accent-dark", "Accent Dark"),
                                        ("dark", "Dark"),
                                        ("light", "Light"),
                                    ],
                                    "help_text": "Choisir la couleur du texte",
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centre"),
                                        ("right", "Droite"),
                                    ],
                                    "help_text": "Choisir l'alignement du texte",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du titre",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ],
                                    "help_text": "Choisir le niveau du titre",
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du paragraphe",
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: ("streams.blocks.ButtonGroupBlock", (), {}),
                            9: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choisir une image", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Petite"),
                                        ("medium", "Moyenne"),
                                        ("large", "Grande"),
                                    ],
                                    "help_text": "Choisir la taille de l'image",
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("lazy", "Lazy (différé)"),
                                        ("eager", "Eager (immédiat)"),
                                    ],
                                    "help_text": "Choisir la méthode de chargement de l'image",
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("alignment", 2),
                                        ("image", 9),
                                        ("alt_text", 10),
                                        ("size", 11),
                                        ("loading", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 9), ("alt_text", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Disposition par défaut"),
                                        ("carousel", "Carrousel"),
                                        ("slider", "Slider"),
                                        ("photography", "Photography"),
                                    ],
                                    "help_text": "Choisir le style de galerie",
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("images", 16), ("style", 17)]],
                                {},
                            ),
                            19: ("wagtail.blocks.RichTextBlock", (), {}),
                            20: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document", "required": False},
                            ),
                            21: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Ajouter un média externe (vidéo, audio, etc.)"
                                },
                            ),
                            22: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Item de liste"},
                            ),
                            24: ("wagtail.blocks.ListBlock", (23,), {}),
                            25: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("Gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {},
                            ),
                            26: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Ajouter un texte ou une description avant les colonnes",
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne gauche",
                                    "required": False,
                                },
                            ),
                            28: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne droite",
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("rich_text", 26),
                                        ("left_column", 27),
                                        ("right_column", 28),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="product.productcategory"
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "tax_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxes.taxproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="product.productpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="productpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="product.ProductPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de l'option (par ex. Petit, Moyen, Grand)",
                        max_length=255,
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix supplémentaire pour cette option (si applicable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "variant",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="product.productvariant",
                    ),
                ),
            ],
        ),
    ]
