# Generated by Django 5.0.9 on 2024-12-01 12:46

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom du transporteur"
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL de l'API",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carriers/logos/",
                        verbose_name="Logo du transporteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="Adresse Ligne 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Adresse Ligne 2",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Code postal"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Ville")),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Région"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom du mode de livraison"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix de base"
                    ),
                ),
                (
                    "per_kg_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix par kg"
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Poids max (kg)"
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("standard", "Livraison Standard"),
                            ("express", "Livraison Express"),
                            ("pickup", "Retrait en magasin"),
                        ],
                        max_length=50,
                        verbose_name="Type de livraison",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_options",
                        to="expeditions.carrier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(max_length=255, verbose_name="ID de commande"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Numéro de suivi",
                    ),
                ),
                (
                    "pdf_label",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="shipping_labels/",
                        verbose_name="Bordereau d'expédition",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Généré le"),
                ),
                (
                    "shipping_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_label",
                        to="expeditions.shippingaddress",
                        verbose_name="Adresse d'expédition",
                    ),
                ),
                (
                    "shipping_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="expeditions.shippingoption",
                    ),
                ),
            ],
        ),
    ]
