# Generated by Django 5.0.9 on 2024-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code ISO"
                    ),
                ),
                (
                    "rate_to_euro",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Taux par rapport à l'Euro",
                    ),
                ),
            ],
        ),
    ]
