# Generated by Django 5.0.9 on 2025-01-09 13:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devises", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="rate_to_euro",
        ),
        migrations.AddField(
            model_name="currency",
            name="gain_exchange_rate",
            field=models.IntegerField(
                default=756, verbose_name="Taux de change (gain)"
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="lose_exchange_rate",
            field=models.IntegerField(
                default=656, verbose_name="Taux de change (perte)"
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Code de la devise"
            ),
        ),
        migrations.CreateModel(
            name="RateCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date du taux de change")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Taux de change"
                    ),
                ),
                (
                    "currency",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="devises.currency",
                        verbose_name="Devise",
                    ),
                ),
            ],
        ),
    ]
