# Generated by Django 5.0.9 on 2025-01-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devises", "0002_remove_currency_rate_to_euro_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Devise", "verbose_name_plural": "Devises"},
        ),
    ]
