# Generated by Django 5.0.9 on 2024-11-28 03:42

import django.db.models.deletion
import taxes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Code ISO"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du pays")),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la région"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code régional"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="taxes.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la ville"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="taxes.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la taxe"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[taxes.validators.validate_tax_rate],
                        verbose_name="Taux (%)",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("reduced", "Réduit"),
                            ("exempt", "Exonéré"),
                            ("zero", "Zéro Rated"),
                        ],
                        default="standard",
                        max_length=50,
                        verbose_name="Type de taxe",
                    ),
                ),
                (
                    "applies_to_foreign",
                    models.BooleanField(default=True, verbose_name="Clients étrangers"),
                ),
                (
                    "applies_to_b2b",
                    models.BooleanField(default=True, verbose_name="Clients B2B"),
                ),
                (
                    "applies_to_b2c",
                    models.BooleanField(default=True, verbose_name="Clients B2C"),
                ),
                (
                    "applies_above_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Seuil minimal (HT)",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        validators=[taxes.validators.validate_dates],
                        verbose_name="Date d'entrée en vigueur",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Version de la taxe"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxes.city",
                        verbose_name="Ville",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="taxes.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxes.region",
                        verbose_name="Région",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                        verbose_name="Site associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxe",
                "verbose_name_plural": "Taxes",
                "indexes": [
                    models.Index(
                        fields=["country", "region", "city", "site", "effective_date"],
                        name="taxes_tax_country_7967ec_idx",
                    )
                ],
                "unique_together": {
                    ("name", "rate", "country", "region", "city", "version")
                },
            },
        ),
    ]
