# Generated by Django 5.0.9 on 2024-12-01 12:46

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la taxe"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux (%)"
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard (20%)"),
                            ("reduced", "Réduit (10%)"),
                            ("super_reduced", "Super Réduit (5.5%)"),
                            ("exempt", "Exonéré"),
                        ],
                        default="standard",
                        max_length=50,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Région"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
        ),
    ]
