# Generated by Django 5.0.9 on 2025-01-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxMatrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux (%)"
                    ),
                ),
                (
                    "tax_account",
                    models.CharField(max_length=100, verbose_name="Compte de taxe"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
        ),
        migrations.CreateModel(
            name="TaxProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(max_length=100, verbose_name="Nom de la taxe"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(max_length=100, verbose_name="Nom de la taxe"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tax",
        ),
        migrations.AddField(
            model_name="taxmatrice",
            name="tax_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taxes.taxproduct"
            ),
        ),
        migrations.AddField(
            model_name="taxmatrice",
            name="tax_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taxes.taxuser"
            ),
        ),
    ]
