# Generated by Django 5.0.9 on 2024-11-01 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="Mon Magasin", max_length=255)),
                (
                    "currency",
                    models.CharField(
                        default="EUR", help_text="Devise (ex : EUR, USD)", max_length=10
                    ),
                ),
                (
                    "tax_rate_default",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Taxe en % par défaut",
                        max_digits=5,
                    ),
                ),
                (
                    "refund_policy",
                    models.TextField(
                        blank=True, help_text="Politique de remboursement", null=True
                    ),
                ),
                ("allow_guest_checkout", models.BooleanField(default=True)),
                (
                    "payment_methods",
                    models.JSONField(
                        default=dict,
                        help_text="Méthodes de paiement activées et leurs configurations (ex : {'stripe': {'enabled': True}})",
                    ),
                ),
                (
                    "erp_integration",
                    models.BooleanField(
                        default=True,
                        help_text="Activer l'intégration ERP/CRM pour suivi des stocks et gestion client",
                    ),
                ),
                (
                    "erp_api_url",
                    models.URLField(
                        blank=True, help_text="URL API de l'ERP/CRM", null=True
                    ),
                ),
                (
                    "erp_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Clé API pour connexion à l'ERP/CRM",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Activer les notifications email pour les commandes",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True,
                        help_text="Serveur SMTP pour l'envoi d'emails",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_port",
                    models.IntegerField(blank=True, help_text="Port SMTP", null=True),
                ),
                (
                    "email_host_user",
                    models.CharField(
                        blank=True,
                        help_text="Utilisateur SMTP",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True,
                        help_text="Mot de passe SMTP",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Stripe", "Stripe"),
                            ("PayPal", "PayPal"),
                            ("COD", "Paiement à la livraison"),
                        ],
                        max_length=50,
                    ),
                ),
                ("delivery_address", models.TextField(blank=True, null=True)),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes spécifiques de la commande pour ERP/CRM",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processed", "Traitée"),
                            ("shipped", "Expédiée"),
                            ("delivered", "Livrée"),
                            ("canceled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes internes pour l'administration",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
