# Generated by Django 5.0.9 on 2024-11-14 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="Mon Magasin", max_length=255)),
                (
                    "currency",
                    models.CharField(
                        default="EUR", help_text="Devise (ex : EUR, USD)", max_length=10
                    ),
                ),
                (
                    "tax_rate_default",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Taxe en % par défaut",
                        max_digits=5,
                    ),
                ),
                (
                    "enable_delivery",
                    models.BooleanField(default=True, help_text="Activer livraison"),
                ),
                (
                    "enable_pickup",
                    models.BooleanField(default=True, help_text="Activer emport"),
                ),
                (
                    "enable_stripe",
                    models.BooleanField(default=True, help_text="Activer Stripe"),
                ),
                (
                    "enable_cod",
                    models.BooleanField(
                        default=True, help_text="Activer Paiement à la livraison (COD)"
                    ),
                ),
                (
                    "stripe_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Clé API secrète de Stripe",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_publishable_key",
                    models.CharField(
                        blank=True,
                        help_text="Clé publique de Stripe",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=False, help_text="Activer les notifications par email"
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        default="Confirmation de commande",
                        help_text="Sujet de l'email de confirmation",
                        max_length=255,
                    ),
                ),
                (
                    "email_body_template",
                    models.TextField(
                        default="Merci pour votre commande #{order_id}. Total : {total} {currency}.",
                        help_text="Modèle d'email de confirmation. Utilisez {order_id}, {total}, {currency} pour les informations.",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True,
                        help_text="Serveur SMTP pour l'envoi d'emails",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_port",
                    models.IntegerField(blank=True, help_text="Port SMTP", null=True),
                ),
                (
                    "email_host_user",
                    models.CharField(
                        blank=True,
                        help_text="Utilisateur SMTP",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True,
                        help_text="Mot de passe SMTP",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        default=dict,
                        help_text="Horaires d'ouverture et jours fermés du magasin.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Stripe", "Stripe"),
                            ("COD", "Paiement à la livraison"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "delivery_option",
                    models.CharField(
                        choices=[("delivery", "Livraison"), ("pickup", "Emport")],
                        max_length=10,
                    ),
                ),
                ("delivery_address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Commandé"),
                            ("paid", "Payé"),
                            ("ready", "Prêt"),
                            ("shipped", "Expédié"),
                            ("delivered", "Livré"),
                            ("canceled", "Annulé"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="ID du PaymentIntent Stripe",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
