# Generated by Django 5.0.9 on 2024-12-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Lundi"),
                            ("tuesday", "Mardi"),
                            ("wednesday", "Mercredi"),
                            ("thursday", "Jeudi"),
                            ("friday", "Vendredi"),
                            ("saturday", "Samedi"),
                            ("sunday", "Dimanche"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, verbose_name="Fermé toute la journée"
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure d'ouverture"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fermeture"
                    ),
                ),
            ],
            options={
                "verbose_name": "Horaire d'ouverture",
                "verbose_name_plural": "Horaires d'ouverture",
            },
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_body_template",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_password",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_user",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_port",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_subject",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_cod",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_email_notifications",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_stripe",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="stripe_api_key",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="stripe_publishable_key",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="opening_hours",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="opening_hours",
            field=models.ManyToManyField(
                blank=True, related_name="store_hours", to="checkout.openinghours"
            ),
        ),
    ]
