# Generated by Django 5.0.9 on 2024-11-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="admin_notes",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="closing_time",
            field=models.TimeField(
                blank=True, help_text="Heure de fermeture", null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="opening_time",
            field=models.TimeField(
                blank=True, help_text="Heure d'ouverture", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_delivered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_paid",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_ready",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Commandé"),
                    ("paid", "Payé"),
                    ("ready", "Prêt"),
                    ("shipped", "Expédié"),
                    ("delivered", "Livré"),
                    ("canceled", "Annulé"),
                ],
                default="ordered",
                max_length=20,
            ),
        ),
    ]
