# Generated by Django 5.0.9 on 2024-12-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_openinghours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_body_template",
            field=models.TextField(
                default="Merci pour votre commande #{order_id}. Total : {total} {currency}.",
                help_text="Modèle d'email de confirmation. Utilisez {order_id}, {total}, {currency} pour les informations.",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host",
            field=models.CharField(
                blank=True,
                help_text="Serveur SMTP pour l'envoi d'emails",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_password",
            field=models.CharField(
                blank=True, help_text="Mot de passe SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="Utilisateur SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_port",
            field=models.IntegerField(blank=True, help_text="Port SMTP", null=True),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_subject",
            field=models.CharField(
                default="Confirmation de commande",
                help_text="Sujet de l'email de confirmation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_cod",
            field=models.BooleanField(
                default=True, help_text="Activer Paiement à la livraison (COD)"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_email_notifications",
            field=models.BooleanField(
                default=False, help_text="Activer les notifications par email"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_stripe",
            field=models.BooleanField(default=True, help_text="Activer Stripe"),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="stripe_api_key",
            field=models.CharField(
                blank=True,
                help_text="Clé API secrète de Stripe",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="stripe_publishable_key",
            field=models.CharField(
                blank=True,
                help_text="Clé publique de Stripe",
                max_length=255,
                null=True,
            ),
        ),
    ]
