# Generated by Django 5.0.9 on 2024-11-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_remove_order_admin_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="erp_api_key",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="erp_api_url",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="erp_integration",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="payment_methods",
        ),
        migrations.RemoveField(
            model_name="order",
            name="additional_notes",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_body_template",
            field=models.TextField(
                default="Merci pour votre commande #{order_id}. Total : {total} {currency}.",
                help_text="Modèle d'email de confirmation. Utilisez {order_id}, {total}, {currency} pour les informations.",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_subject",
            field=models.CharField(
                default="Confirmation de commande",
                help_text="Sujet de l'email de confirmation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_cod",
            field=models.BooleanField(
                default=True, help_text="Paiement à la livraison (COD)"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_paypal",
            field=models.BooleanField(default=True, help_text="Activer PayPal"),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_stripe",
            field=models.BooleanField(default=True, help_text="Activer Stripe"),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="paypal_client_id",
            field=models.CharField(
                blank=True, help_text="Client ID PayPal", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="paypal_secret_key",
            field=models.CharField(
                blank=True, help_text="Secret Key PayPal", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="stripe_api_key",
            field=models.CharField(
                blank=True, help_text="Clé API de Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_email_notifications",
            field=models.BooleanField(
                default=True, help_text="Activer les notifications par email"
            ),
        ),
    ]
