# Generated by Django 5.0.9 on 2024-12-26 13:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_checkoutsettings_email_body_template_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="opening_hours",
        ),
        migrations.DeleteModel(
            name="OpeningHours",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="opening_hours",
            field=wagtail.fields.StreamField(
                [("opening_hours", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("monday", "Lundi"),
                                ("tuesday", "Mardi"),
                                ("wednesday", "Mercredi"),
                                ("thursday", "Jeudi"),
                                ("friday", "Vendredi"),
                                ("saturday", "Samedi"),
                                ("sunday", "Dimanche"),
                            ],
                            "label": "Jour",
                        },
                    ),
                    1: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {
                            "help_text": "Format HH:MM",
                            "label": "Heure d'ouverture",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {
                            "help_text": "Format HH:MM",
                            "label": "Heure de fermeture",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {
                            "help_text": "Format HH:MM (facultatif)",
                            "label": "Deuxième créneau d'ouverture",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {
                            "help_text": "Format HH:MM (facultatif)",
                            "label": "Deuxième créneau de fermeture",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Cocher si l'entreprise est fermée toute la journée",
                            "label": "Fermé toute la journée",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("day", 0),
                                ("open_time", 1),
                                ("close_time", 2),
                                ("second_open_time", 3),
                                ("second_close_time", 4),
                                ("closed", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
