# Generated by Django 5.0.9 on 2024-11-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_remove_checkoutsettings_erp_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_password",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_user",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_port",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_cod",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="opening_time",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="refund_policy",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_delivery",
            field=models.BooleanField(default=True, help_text="Activer la livraison"),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_pickup",
            field=models.BooleanField(default=True, help_text="Activer le retrait"),
        ),
    ]
