# Generated by Django 5.0.9 on 2024-12-27 18:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_remove_checkoutsettings_opening_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_password",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_user",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_port",
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="email_body_template",
            field=wagtail.fields.RichTextField(
                default="Merci pour votre commande #{order_id}. Total : {total} {currency}.",
                help_text="Modèle d'email de confirmation. Utilisez {order_id}, {total}, {currency} pour les informations.",
            ),
        ),
    ]
