# Generated by Django 5.0.9 on 2024-11-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_remove_checkoutsettings_closing_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_delivery",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_pickup",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="closing_time",
            field=models.TimeField(
                blank=True, help_text="Heure de fermeture", null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host",
            field=models.CharField(
                blank=True,
                help_text="Serveur SMTP pour l'envoi d'emails",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_password",
            field=models.CharField(
                blank=True, help_text="Mot de passe SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="Utilisateur SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_port",
            field=models.IntegerField(blank=True, help_text="Port SMTP", null=True),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_cod",
            field=models.BooleanField(
                default=True, help_text="Paiement à la livraison (COD)"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="opening_time",
            field=models.TimeField(
                blank=True, help_text="Heure d'ouverture", null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="refund_policy",
            field=models.TextField(
                blank=True, help_text="Politique de remboursement", null=True
            ),
        ),
    ]
