# Generated by Django 5.0.9 on 2024-11-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_remove_checkoutsettings_enable_delivery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_password",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_user",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_port",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="refund_policy",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="delivery_options",
            field=models.BooleanField(
                default=True, help_text="Activer les options de livraison"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="pickup_options",
            field=models.BooleanField(
                default=True, help_text="Activer l'option d'emport"
            ),
        ),
    ]
