# Generated by Django 5.0.9 on 2025-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_remove_checkoutsettings_email_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsettings",
            name="daily_exchange_rate",
            field=models.BooleanField(
                default=True,
                help_text="Activer la conversion quotidienne. Mensuel par défault.",
            ),
        ),
    ]
