# Generated by Django 5.0.9 on 2024-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_remove_checkoutsettings_email_host_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="delivery_options",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="pickup_options",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date_delivered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date_ready",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date_shipped",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="closed_days",
            field=models.CharField(
                blank=True,
                help_text="Jours où le magasin est fermé (ex : Lundi, Dimanche)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host",
            field=models.CharField(
                blank=True,
                help_text="Serveur SMTP pour l'envoi d'emails",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_password",
            field=models.CharField(
                blank=True, help_text="Mot de passe SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="Utilisateur SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_port",
            field=models.IntegerField(blank=True, help_text="Port SMTP", null=True),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_use_tls",
            field=models.BooleanField(
                default=False, help_text="Utiliser TLS pour l'envoi d'emails"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_delivery",
            field=models.BooleanField(
                default=False, help_text="Activer l'option de livraison"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_pickup",
            field=models.BooleanField(
                default=False, help_text="Activer l'option de retrait"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                choices=[("delivery", "Livraison"), ("pickup", "Retrait")],
                default="delivery",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="allow_guest_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_cod",
            field=models.BooleanField(
                default=False, help_text="Activer le paiement à la livraison"
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_email_notifications",
            field=models.BooleanField(
                default=False, help_text="Activer les notifications par email"
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_paypal",
            field=models.BooleanField(default=False, help_text="Activer PayPal"),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_stripe",
            field=models.BooleanField(default=False, help_text="Activer Stripe"),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default="contact@zatchouli.fr", max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="06 00 00 00 00", max_length=15),
        ),
    ]
