# Generated by Django 5.0.9 on 2024-11-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0007_remove_checkoutsettings_delivery_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="allow_guest_checkout",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_body_template",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_password",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_host_user",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_port",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_subject",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="email_use_tls",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_email_notifications",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date_updated",
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="closed_days",
            field=models.TextField(
                blank=True, help_text="Jours fermés (ex: Monday, Tuesday)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="currency",
            field=models.CharField(default="EUR", max_length=10),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_cod",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_delivery",
            field=models.BooleanField(default=False, help_text="Activer livraison"),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_paypal",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_pickup",
            field=models.BooleanField(default=False, help_text="Activer emport"),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_stripe",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="paypal_client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="paypal_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="stripe_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="tax_rate_default",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                choices=[("delivery", "Livraison"), ("pickup", "Emport")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Stripe", "Stripe"),
                    ("PayPal", "PayPal"),
                    ("COD", "Paiement à la livraison"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
