# Generated by Django 5.0.9 on 2024-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0008_remove_checkoutsettings_allow_guest_checkout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_body_template",
            field=models.TextField(
                default="Merci pour votre commande #{order_id}. Total : {total} {currency}.",
                help_text="Modèle d'email de confirmation. Utilisez {order_id}, {total}, {currency} pour les informations.",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host",
            field=models.CharField(
                blank=True,
                help_text="Serveur SMTP pour l'envoi d'emails",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_password",
            field=models.CharField(
                blank=True, help_text="Mot de passe SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="Utilisateur SMTP", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_port",
            field=models.IntegerField(blank=True, help_text="Port SMTP", null=True),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="email_subject",
            field=models.CharField(
                default="Confirmation de commande",
                help_text="Sujet de l'email de confirmation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="enable_email_notifications",
            field=models.BooleanField(
                default=False, help_text="Activer les notifications par email"
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="closing_time",
            field=models.TimeField(
                blank=True, help_text="Heure de fermeture", null=True
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="currency",
            field=models.CharField(
                default="EUR", help_text="Devise (ex : EUR, USD)", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_cod",
            field=models.BooleanField(
                default=True, help_text="Activer Paiement à la livraison (COD)"
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_delivery",
            field=models.BooleanField(default=True, help_text="Activer livraison"),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_paypal",
            field=models.BooleanField(default=True, help_text="Activer PayPal"),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_pickup",
            field=models.BooleanField(default=True, help_text="Activer emport"),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="enable_stripe",
            field=models.BooleanField(default=True, help_text="Activer Stripe"),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="opening_time",
            field=models.TimeField(
                blank=True, help_text="Heure d'ouverture", null=True
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="paypal_client_id",
            field=models.CharField(
                blank=True, help_text="Client ID PayPal", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="paypal_secret_key",
            field=models.CharField(
                blank=True, help_text="Secret Key PayPal", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="stripe_api_key",
            field=models.CharField(
                blank=True, help_text="Clé API de Stripe", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="tax_rate_default",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Taxe en % par défaut",
                max_digits=5,
            ),
        ),
    ]
