# Generated by Django 5.0.9 on 2024-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0009_checkoutsettings_email_body_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Lundi"),
                            ("Tuesday", "Mardi"),
                            ("Wednesday", "Mercredi"),
                            ("Thursday", "Jeudi"),
                            ("Friday", "Vendredi"),
                            ("Saturday", "Samedi"),
                            ("Sunday", "Dimanche"),
                        ],
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez si le magasin est fermé ce jour",
                    ),
                ),
                ("morning_opening", models.TimeField(blank=True, null=True)),
                ("morning_closing", models.TimeField(blank=True, null=True)),
                ("evening_opening", models.TimeField(blank=True, null=True)),
                ("evening_closing", models.TimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Horaire d'ouverture",
                "verbose_name_plural": "Horaires d'ouverture",
            },
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="closed_days",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="enable_paypal",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="opening_time",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="paypal_client_id",
        ),
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="paypal_secret_key",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Stripe", "Stripe"), ("COD", "Paiement à la livraison")],
                max_length=50,
            ),
        ),
    ]
