# Generated by Django 5.0.9 on 2024-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0010_openinghours_remove_checkoutsettings_closed_days_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpeningHours",
        ),
        migrations.AddField(
            model_name="checkoutsettings",
            name="opening_hours",
            field=models.JSONField(
                default=dict,
                help_text="Horaires d'ouverture pour chaque jour de la semaine.",
            ),
        ),
    ]
