# Generated by Django 5.0.9 on 2024-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0011_delete_openinghours_checkoutsettings_opening_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsettings",
            name="closed_days",
            field=models.TextField(
                blank=True, help_text="Jours fermés (ex: Monday, Tuesday)", null=True
            ),
        ),
    ]
