# Generated by Django 5.0.9 on 2024-11-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0012_checkoutsettings_closed_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsettings",
            name="closed_days",
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="opening_hours",
            field=models.JSONField(
                default=dict,
                help_text="Horaires d'ouverture et jours fermés du magasin.",
            ),
        ),
    ]
