# Generated by Django 5.0.9 on 2024-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0013_remove_checkoutsettings_closed_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsettings",
            name="stripe_publishable_key",
            field=models.CharField(
                blank=True,
                help_text="Clé publique de Stripe",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="ID du PaymentIntent Stripe",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsettings",
            name="stripe_api_key",
            field=models.CharField(
                blank=True,
                help_text="Clé API secrète de Stripe",
                max_length=255,
                null=True,
            ),
        ),
    ]
