# Generated by Django 5.0.9 on 2024-11-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0014_checkoutsettings_stripe_publishable_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date_created"]},
        ),
    ]
