# Generated by Django 5.0.9 on 2024-10-22 05:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Résumé de la catégorie"),
                ),
                ("content", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("single_column", 25),
                            ("double_column", 29),
                            ("paginated_services", 31),
                            ("limited_services", 34),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("normal", "Espacement normal"),
                                        ("large", "Grand espacement"),
                                    ],
                                    "help_text": "Choisir l'espacement entre les éléments",
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("primary-light", "Primary Light"),
                                        ("primary-dark", "Primary Dark"),
                                        ("secondary", "Secondary"),
                                        ("secondary-light", "Secondary Light"),
                                        ("secondary-dark", "Secondary Dark"),
                                        ("accent", "Accent"),
                                        ("accent-light", "Accent Light"),
                                        ("accent-dark", "Accent Dark"),
                                        ("dark", "Dark"),
                                        ("light", "Light"),
                                    ],
                                    "help_text": "Choisir la couleur du texte",
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centre"),
                                        ("right", "Droite"),
                                    ],
                                    "help_text": "Choisir l'alignement du texte",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du titre",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ],
                                    "help_text": "Choisir le niveau du titre",
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du paragraphe",
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: ("streams.blocks.ButtonGroupBlock", (), {}),
                            9: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choisir une image", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Petite"),
                                        ("medium", "Moyenne"),
                                        ("large", "Grande"),
                                    ],
                                    "help_text": "Choisir la taille de l'image",
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("lazy", "Lazy (différé)"),
                                        ("eager", "Eager (immédiat)"),
                                    ],
                                    "help_text": "Choisir la méthode de chargement de l'image",
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("alignment", 2),
                                        ("image", 9),
                                        ("alt_text", 10),
                                        ("size", 11),
                                        ("loading", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 9), ("alt_text", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Disposition par défaut"),
                                        ("carousel", "Carrousel"),
                                        ("slider", "Slider"),
                                        ("photography", "Photography"),
                                    ],
                                    "help_text": "Choisir le style de galerie",
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("images", 16), ("style", 17)]],
                                {},
                            ),
                            19: ("wagtail.blocks.RichTextBlock", (), {}),
                            20: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document", "required": False},
                            ),
                            21: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Ajouter un média externe (vidéo, audio, etc.)"
                                },
                            ),
                            22: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Item de liste"},
                            ),
                            24: ("wagtail.blocks.ListBlock", (23,), {}),
                            25: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("Gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {},
                            ),
                            26: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Ajouter un texte ou une description avant les colonnes",
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne gauche",
                                    "required": False,
                                },
                            ),
                            28: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne droite",
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("rich_text", 26),
                                        ("left_column", 27),
                                        ("right_column", 28),
                                    ]
                                ],
                                {},
                            ),
                            30: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de services à afficher par page",
                                },
                            ),
                            31: ("wagtail.blocks.StructBlock", [[("limit", 30)]], {}),
                            32: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de services à afficher",
                                },
                            ),
                            33: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les services mis en avant",
                                    "required": False,
                                },
                            ),
                            34: (
                                "wagtail.blocks.StructBlock",
                                [[("limit", 32), ("featured_only", 33)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie de service",
                "verbose_name_plural": "Catégories de services",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Résumé du service"),
                ),
                ("content", wagtail.fields.RichTextField(blank=True)),
                (
                    "area_served",
                    models.CharField(
                        blank=True,
                        help_text="Zone desservie (ville ou région)",
                        max_length=255,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Mettre ce service en avant"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("single_column", 25),
                            ("double_column", 29),
                            ("siblings_service_list", 31),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("normal", "Espacement normal"),
                                        ("large", "Grand espacement"),
                                    ],
                                    "help_text": "Choisir l'espacement entre les éléments",
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("primary-light", "Primary Light"),
                                        ("primary-dark", "Primary Dark"),
                                        ("secondary", "Secondary"),
                                        ("secondary-light", "Secondary Light"),
                                        ("secondary-dark", "Secondary Dark"),
                                        ("accent", "Accent"),
                                        ("accent-light", "Accent Light"),
                                        ("accent-dark", "Accent Dark"),
                                        ("dark", "Dark"),
                                        ("light", "Light"),
                                    ],
                                    "help_text": "Choisir la couleur du texte",
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centre"),
                                        ("right", "Droite"),
                                    ],
                                    "help_text": "Choisir l'alignement du texte",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du titre",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ],
                                    "help_text": "Choisir le niveau du titre",
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du paragraphe",
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: ("streams.blocks.ButtonGroupBlock", (), {}),
                            9: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choisir une image", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Petite"),
                                        ("medium", "Moyenne"),
                                        ("large", "Grande"),
                                    ],
                                    "help_text": "Choisir la taille de l'image",
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("lazy", "Lazy (différé)"),
                                        ("eager", "Eager (immédiat)"),
                                    ],
                                    "help_text": "Choisir la méthode de chargement de l'image",
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("alignment", 2),
                                        ("image", 9),
                                        ("alt_text", 10),
                                        ("size", 11),
                                        ("loading", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 9), ("alt_text", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Disposition par défaut"),
                                        ("carousel", "Carrousel"),
                                        ("slider", "Slider"),
                                        ("photography", "Photography"),
                                    ],
                                    "help_text": "Choisir le style de galerie",
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("images", 16), ("style", 17)]],
                                {},
                            ),
                            19: ("wagtail.blocks.RichTextBlock", (), {}),
                            20: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document", "required": False},
                            ),
                            21: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Ajouter un média externe (vidéo, audio, etc.)"
                                },
                            ),
                            22: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Item de liste"},
                            ),
                            24: ("wagtail.blocks.ListBlock", (23,), {}),
                            25: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("Gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {},
                            ),
                            26: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Ajouter un texte ou une description avant les colonnes",
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne gauche",
                                    "required": False,
                                },
                            ),
                            28: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("buttons", 8),
                                        ("image", 13),
                                        ("gallery", 18),
                                        ("richtext", 19),
                                        ("document", 20),
                                        ("embed", 21),
                                        ("quote", 22),
                                        ("list", 24),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne droite",
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("rich_text", 26),
                                        ("left_column", 27),
                                        ("right_column", 28),
                                    ]
                                ],
                                {},
                            ),
                            30: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 3,
                                    "help_text": "Nombre de services siblings à afficher",
                                },
                            ),
                            31: ("wagtail.blocks.StructBlock", [[("limit", 30)]], {}),
                        },
                        null=True,
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
            bases=("wagtailcore.page",),
        ),
    ]
