# Generated by Django 5.0.9 on 2024-10-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Contenu de l'accueil"),
                ),
                ("cta_text", models.CharField(blank=True, max_length=50)),
                ("cta_url", models.URLField(blank=True)),
                (
                    "cta_style",
                    models.CharField(
                        choices=[
                            ("btn1", "Bouton 1"),
                            ("btn2", "Bouton 2"),
                            ("btn3", "Bouton 3"),
                        ],
                        default="btn1",
                        help_text="Choisir le style du bouton",
                        max_length=20,
                    ),
                ),
                (
                    "cta_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image de l'accueil",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
