# Generated by Django 5.0.9 on 2024-11-14 18:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("paginated_product_list", 11),
                            ("limited_product_list", 14),
                            ("paginated_product_category_list", 16),
                            ("limited_product_category_list", 19),
                            ("paginated_blog_list", 23),
                            ("limited_blog_list", 26),
                            ("paginated_blog_category_list", 28),
                            ("limited_blog_category_list", 31),
                            ("single_column", 51),
                            ("double_column", 55),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("normal", "Espacement normal"),
                                        ("large", "Grand espacement"),
                                    ],
                                    "help_text": "Choisir l'espacement entre les éléments",
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("primary-light", "Primary Light"),
                                        ("primary-dark", "Primary Dark"),
                                        ("secondary", "Secondary"),
                                        ("secondary-light", "Secondary Light"),
                                        ("secondary-dark", "Secondary Dark"),
                                        ("accent", "Accent"),
                                        ("accent-light", "Accent Light"),
                                        ("accent-dark", "Accent Dark"),
                                        ("dark", "Dark"),
                                        ("light", "Light"),
                                    ],
                                    "help_text": "Choisir la couleur du texte",
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Gauche"),
                                        ("center", "Centre"),
                                        ("right", "Droite"),
                                    ],
                                    "help_text": "Choisir l'alignement du texte",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du titre",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ],
                                    "help_text": "Choisir le niveau du titre",
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {
                                    "help_text": "Titre facultatif pour cette section",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Ajouter le texte du paragraphe",
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {
                                    "help_text": "Texte facultatif pour cette section",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 6,
                                    "help_text": "Nombre de produits par page",
                                },
                            ),
                            9: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["product.ProductCategory"]},
                            ),
                            10: (
                                "wagtail.blocks.ListBlock",
                                (9,),
                                {
                                    "help_text": "Choisissez les catégories pour filtrer les produits",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 8),
                                        ("categories", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de produits à afficher",
                                },
                            ),
                            13: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les produits vedettes",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 12),
                                        ("featured_only", 13),
                                        ("categories", 10),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 6,
                                    "help_text": "Nombre de catégories de produits par page",
                                },
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 5), ("paragraph", 7), ("limit", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de catégories de produits à afficher",
                                },
                            ),
                            18: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les catégories vedettes",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 17),
                                        ("featured_only", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre d'articles de blog par page",
                                },
                            ),
                            21: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["blog.BlogCategoryPage"]},
                            ),
                            22: (
                                "wagtail.blocks.ListBlock",
                                (21,),
                                {
                                    "help_text": "Choisissez les catégories pour filtrer les articles",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 20),
                                        ("categories", 22),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre d'articles de blog à afficher",
                                },
                            ),
                            25: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les articles en vedette",
                                    "required": False,
                                },
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 24),
                                        ("featured_only", 25),
                                        ("categories", 22),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de catégories de blog par page",
                                },
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 5), ("paragraph", 7), ("limit", 27)]],
                                {},
                            ),
                            29: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Nombre de catégories de blog à afficher",
                                },
                            ),
                            30: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Afficher uniquement les catégories en vedette",
                                    "required": False,
                                },
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("paragraph", 7),
                                        ("limit", 29),
                                        ("featured_only", 30),
                                    ]
                                ],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("heading_text", 3),
                                        ("heading_level", 4),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("color", 1),
                                        ("alignment", 2),
                                        ("text", 6),
                                    ]
                                ],
                                {},
                            ),
                            34: ("streams.blocks.ButtonGroupBlock", (), {}),
                            35: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Choisir une image", "required": True},
                            ),
                            36: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            37: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Petite"),
                                        ("medium", "Moyenne"),
                                        ("large", "Grande"),
                                    ],
                                    "help_text": "Choisir la taille de l'image",
                                },
                            ),
                            38: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("lazy", "Lazy (différé)"),
                                        ("eager", "Eager (immédiat)"),
                                    ],
                                    "help_text": "Choisir la méthode de chargement de l'image",
                                },
                            ),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("alignment", 2),
                                        ("image", 35),
                                        ("alt_text", 36),
                                        ("size", 37),
                                        ("loading", 38),
                                    ]
                                ],
                                {},
                            ),
                            40: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Texte alternatif pour l'image",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 35), ("alt_text", 40)]],
                                {},
                            ),
                            42: ("wagtail.blocks.ListBlock", (41,), {}),
                            43: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Disposition par défaut"),
                                        ("carousel", "Carrousel"),
                                        ("slider", "Slider"),
                                        ("photography", "Photography"),
                                    ],
                                    "help_text": "Choisir le style de galerie",
                                },
                            ),
                            44: (
                                "wagtail.blocks.StructBlock",
                                [[("images", 42), ("style", 43)]],
                                {},
                            ),
                            45: ("wagtail.blocks.RichTextBlock", (), {}),
                            46: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document", "required": False},
                            ),
                            47: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Ajouter un média externe (vidéo, audio, etc.)"
                                },
                            ),
                            48: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            49: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Item de liste"},
                            ),
                            50: ("wagtail.blocks.ListBlock", (49,), {}),
                            51: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 32),
                                        ("paragraph", 33),
                                        ("buttons", 34),
                                        ("image", 39),
                                        ("Gallery", 44),
                                        ("richtext", 45),
                                        ("document", 46),
                                        ("embed", 47),
                                        ("quote", 48),
                                        ("list", 50),
                                    ]
                                ],
                                {},
                            ),
                            52: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Ajouter un texte ou une description avant les colonnes",
                                    "required": False,
                                },
                            ),
                            53: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 32),
                                        ("paragraph", 33),
                                        ("buttons", 34),
                                        ("image", 39),
                                        ("gallery", 44),
                                        ("richtext", 45),
                                        ("document", 46),
                                        ("embed", 47),
                                        ("quote", 48),
                                        ("list", 50),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne gauche",
                                    "required": False,
                                },
                            ),
                            54: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 32),
                                        ("paragraph", 33),
                                        ("buttons", 34),
                                        ("image", 39),
                                        ("gallery", 44),
                                        ("richtext", 45),
                                        ("document", 46),
                                        ("embed", 47),
                                        ("quote", 48),
                                        ("list", 50),
                                    ]
                                ],
                                {
                                    "help_text": "Ajouter des blocs à la colonne droite",
                                    "required": False,
                                },
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("rich_text", 52),
                                        ("left_column", 53),
                                        ("right_column", 54),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Flex Page",
                "verbose_name_plural": "Flex Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
