# Generated by Django 5.0.9 on 2024-10-21 00:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("single_column", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Ajouter du texte enrichi", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Ajouter une image", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Texte du bouton", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Lien du bouton", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 2), ("url", 3)]],
                        {"help_text": "Ajouter un bouton", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StreamBlock",
                        [[("richtext", 0), ("image", 1), ("button", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
