# Generated by Django 5.0.9 on 2024-10-21 00:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0002_alter_flexpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flexpage",
            name="subtitle",
        ),
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Ajouter le texte du titre", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                                ("h5", "H5"),
                                ("h6", "H6"),
                            ],
                            "help_text": "Choisir le niveau du titre",
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Gauche"),
                                ("center", "Centre"),
                                ("right", "Droite"),
                            ],
                            "help_text": "Choisir l'alignement du titre",
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                                ("dark", "Dark"),
                                ("light", "Light"),
                            ],
                            "help_text": "Choisir la couleur du titre",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading_text", 0),
                                ("heading_level", 1),
                                ("alignment", 2),
                                ("color", 3),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
