# Generated by Django 5.0.9 on 2024-10-21 01:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0003_remove_flexpage_subtitle_alter_flexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("normal", "Espacement normal"),
                                ("large", "Grand espacement"),
                            ],
                            "help_text": "Choisir l'espacement entre les éléments",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("primary-light", "Primary Light"),
                                ("primary-dark", "Primary Dark"),
                                ("secondary", "Secondary"),
                                ("secondary-light", "Secondary Light"),
                                ("secondary-dark", "Secondary Dark"),
                                ("accent", "Accent"),
                                ("accent-light", "Accent Light"),
                                ("accent-dark", "Accent Dark"),
                                ("dark", "Dark"),
                                ("light", "Light"),
                            ],
                            "help_text": "Choisir la couleur du texte",
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Gauche"),
                                ("center", "Centre"),
                                ("right", "Droite"),
                            ],
                            "help_text": "Choisir l'alignement du texte",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Ajouter le texte du titre", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                                ("h5", "H5"),
                                ("h6", "H6"),
                            ],
                            "help_text": "Choisir le niveau du titre",
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("spacing", 0),
                                ("color", 1),
                                ("alignment", 2),
                                ("heading_text", 3),
                                ("heading_level", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
