# Generated by Django 5.0.9 on 2024-10-21 01:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0007_alter_flexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 5),
                    ("paragraph", 7),
                    ("button", 12),
                    ("image", 17),
                    ("gallery", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("normal", "Espacement normal"),
                                ("large", "Grand espacement"),
                            ],
                            "help_text": "Choisir l'espacement entre les éléments",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("primary-light", "Primary Light"),
                                ("primary-dark", "Primary Dark"),
                                ("secondary", "Secondary"),
                                ("secondary-light", "Secondary Light"),
                                ("secondary-dark", "Secondary Dark"),
                                ("accent", "Accent"),
                                ("accent-light", "Accent Light"),
                                ("accent-dark", "Accent Dark"),
                                ("dark", "Dark"),
                                ("light", "Light"),
                            ],
                            "help_text": "Choisir la couleur du texte",
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Gauche"),
                                ("center", "Centre"),
                                ("right", "Droite"),
                            ],
                            "help_text": "Choisir l'alignement du texte",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Ajouter le texte du titre", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                                ("h5", "H5"),
                                ("h6", "H6"),
                            ],
                            "help_text": "Choisir le niveau du titre",
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("spacing", 0),
                                ("color", 1),
                                ("alignment", 2),
                                ("heading_text", 3),
                                ("heading_level", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Ajouter le texte du paragraphe",
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 0), ("color", 1), ("alignment", 2), ("text", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Texte du bouton", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Sélectionner une page interne",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Ou entrer une URL externe (si aucune page n'est sélectionnée)",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("btn-primary", "Primary"),
                                ("btn-secondary", "Secondary"),
                                ("btn-accent", "Accent"),
                            ],
                            "help_text": "Choisir le style du bouton",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 8), ("link", 9), ("url", 10), ("style", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Choisir une image", "required": True},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Texte alternatif pour l'image",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Petite"),
                                ("medium", "Moyenne"),
                                ("large", "Grande"),
                            ],
                            "help_text": "Choisir la taille de l'image",
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("lazy", "Lazy (différé)"),
                                ("eager", "Eager (immédiat)"),
                            ],
                            "help_text": "Choisir la méthode de chargement de l'image",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("spacing", 0),
                                ("alignment", 2),
                                ("image", 13),
                                ("alt_text", 14),
                                ("size", 15),
                                ("loading", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Texte alternatif pour l'image",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 13), ("alt_text", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Disposition par défaut"),
                                ("carousel", "Carrousel"),
                                ("slider", "Slider"),
                            ],
                            "help_text": "Choisir le style de galerie",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("images", 20), ("style", 21)]],
                        {},
                    ),
                },
            ),
        ),
    ]
