# Generated by Django 5.0.9 on 2024-11-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMTPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(max_length=255, verbose_name="Email Host"),
                ),
                ("email_port", models.PositiveIntegerField(verbose_name="Email Port")),
                (
                    "email_host_user",
                    models.CharField(max_length=255, verbose_name="Email Host User"),
                ),
                (
                    "email_host_password",
                    models.TextField(verbose_name="Email Host Password"),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="Use TLS")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="Use SSL")),
                (
                    "test_email_recipient",
                    models.EmailField(
                        default="admin@example.com",
                        help_text="Enter the email address to receive the test email.",
                        max_length=254,
                        verbose_name="Test Email Recipient",
                    ),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(
                        default=False, verbose_name="Password Encrypted"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMTP Settings",
                "verbose_name_plural": "SMTP Settings",
            },
        ),
    ]
