# Generated by Django 5.0.9 on 2024-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smtp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smtpsettings",
            name="email_port",
            field=models.PositiveIntegerField(
                blank=True,
                default=587,
                help_text="Le port utilisé pour la connexion SMTP (par exemple : 587 pour TLS).",
                null=True,
                verbose_name="Email Port",
            ),
        ),
    ]
