# Generated by Django 5.0.9 on 2024-11-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smtp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smtpsettings",
            name="email_port",
            field=models.PositiveIntegerField(default=587, verbose_name="Email Port"),
        ),
    ]
