# Generated by Django 5.0.9 on 2024-11-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smtp", "0002_alter_smtpsettings_email_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smtpsettings",
            name="is_encrypted",
        ),
        migrations.AlterField(
            model_name="smtpsettings",
            name="email_port",
            field=models.PositiveIntegerField(verbose_name="Email Port"),
        ),
    ]
