# Generated by Django 5.0.9 on 2024-11-14 18:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_contact",
                    models.CharField(
                        help_text="Nom du contact principal", max_length=255
                    ),
                ),
                (
                    "telephone",
                    models.CharField(help_text="Numéro de téléphone", max_length=20),
                ),
                ("email", models.EmailField(help_text="Adresse email", max_length=254)),
                (
                    "adresse_rue_contact",
                    models.CharField(
                        help_text="Rue de l'adresse de contact", max_length=255
                    ),
                ),
                (
                    "adresse_code_postal_contact",
                    models.CharField(
                        help_text="Code postal de l'adresse de contact", max_length=10
                    ),
                ),
                (
                    "adresse_ville_contact",
                    models.CharField(
                        help_text="Ville de l'adresse de contact", max_length=100
                    ),
                ),
                (
                    "adresse_pays_contact",
                    models.CharField(
                        help_text="Pays de l'adresse de contact", max_length=100
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HorairesOuverture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MentionsLegalesSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hebergeur_nom",
                    models.CharField(help_text="Nom de l'hébergeur", max_length=255),
                ),
                (
                    "hebergeur_adresse_rue",
                    models.CharField(
                        help_text="Rue de l'adresse de l'hébergeur", max_length=255
                    ),
                ),
                (
                    "hebergeur_adresse_code_postal",
                    models.CharField(
                        help_text="Code postal de l'hébergeur", max_length=10
                    ),
                ),
                (
                    "hebergeur_adresse_ville",
                    models.CharField(help_text="Ville de l'hébergeur", max_length=100),
                ),
                (
                    "hebergeur_adresse_pays",
                    models.CharField(help_text="Pays de l'hébergeur", max_length=100),
                ),
                (
                    "hebergeur_contact",
                    models.CharField(help_text="Contact de l'hébergeur", max_length=50),
                ),
                (
                    "responsable_publication",
                    models.CharField(
                        help_text="Nom du responsable de la publication", max_length=255
                    ),
                ),
                (
                    "proprietaire_site",
                    models.CharField(
                        help_text="Nom du propriétaire du site", max_length=255
                    ),
                ),
                (
                    "cgu_url",
                    models.URLField(
                        blank=True,
                        help_text="URL vers les conditions générales d'utilisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganisationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_entreprise",
                    models.CharField(help_text="Nom de l'entreprise", max_length=255),
                ),
                (
                    "numero_siret",
                    models.CharField(help_text="Numéro de SIRET", max_length=14),
                ),
                (
                    "numero_tva",
                    models.CharField(
                        blank=True, help_text="Numéro de TVA", max_length=50
                    ),
                ),
                (
                    "capital_social",
                    models.CharField(
                        blank=True,
                        help_text="Capital social de l'entreprise",
                        max_length=50,
                    ),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        blank=True,
                        help_text="Forme juridique (SARL, SAS, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "adresse_rue",
                    models.CharField(
                        help_text="Rue de l'adresse du siège social", max_length=255
                    ),
                ),
                (
                    "adresse_code_postal",
                    models.CharField(help_text="Code postal", max_length=10),
                ),
                ("adresse_ville", models.CharField(help_text="Ville", max_length=100)),
                ("adresse_pays", models.CharField(help_text="Pays", max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartenairesSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="URL du profil Instagram"),
                ),
                (
                    "tiktok_url",
                    models.URLField(blank=True, help_text="URL du profil TikTok"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="URL du profil LinkedIn"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Horaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("Lundi", "Lundi"),
                            ("Mardi", "Mardi"),
                            ("Mercredi", "Mercredi"),
                            ("Jeudi", "Jeudi"),
                            ("Vendredi", "Vendredi"),
                            ("Samedi", "Samedi"),
                            ("Dimanche", "Dimanche"),
                        ],
                        help_text="Jour de la semaine",
                        max_length=20,
                    ),
                ),
                (
                    "heure_debut",
                    models.TimeField(
                        blank=True,
                        help_text="Heure d'ouverture (laisser vide si fermé).",
                        null=True,
                    ),
                ),
                (
                    "heure_fin",
                    models.TimeField(
                        blank=True,
                        help_text="Heure de fermeture (laisser vide si fermé).",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horaires",
                        to="site_settings.horairesouverture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horaire",
                "verbose_name_plural": "Horaires",
            },
        ),
        migrations.CreateModel(
            name="MediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_alt",
                    models.CharField(
                        help_text="Texte alternatif pour le logo", max_length=255
                    ),
                ),
                (
                    "favicon_alt",
                    models.CharField(
                        help_text="Texte alternatif pour le favicon", max_length=255
                    ),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Favicon du site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo de l'entreprise",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partenaire_nom",
                    models.CharField(help_text="Nom du partenaire", max_length=255),
                ),
                (
                    "partenaire_url",
                    models.URLField(help_text="Lien vers le site du partenaire"),
                ),
                (
                    "partenaire_alt",
                    models.CharField(
                        help_text="Texte alternatif pour le logo du partenaire",
                        max_length=255,
                    ),
                ),
                (
                    "partenaire_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo du partenaire",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partenaires",
                        to="site_settings.partenairessettings",
                    ),
                ),
            ],
        ),
    ]
