# Generated by Django 5.0.9 on 2024-11-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.productpage"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="selected_options",
            field=models.ManyToManyField(blank=True, to="product.variantoption"),
        ),
    ]
