# Generated by Django 5.0.9 on 2024-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("product", "0002_remove_productvariant_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="selected_options",
            field=models.ManyToManyField(blank=True, to="product.variantoption"),
        ),
    ]
