# Generated by Django 5.0.9 on 2024-11-18 04:31

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nom du menu (ex : MenuHeader, MenuFooter1, etc.)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Texte affiché pour le lien.", max_length=255
                    ),
                ),
                (
                    "custom_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien personnalisé si aucune page n'est sélectionnée.",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Ordre d'affichage."),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page Wagtail à laquelle ce lien pointe.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Élément parent pour créer des sous-menus.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="layout.navigationitem",
                    ),
                ),
                (
                    "menu",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        help_text="Menu auquel cet élément appartient.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="layout.navigationmenu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeaderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_logo",
                    models.BooleanField(
                        default=True, help_text="Afficher le logo dans le Header"
                    ),
                ),
                (
                    "display_site_title",
                    models.BooleanField(
                        default=True,
                        help_text="Afficher le titre du site dans le Header",
                    ),
                ),
                (
                    "display_menu",
                    models.BooleanField(
                        default=True, help_text="Afficher le menu de navigation"
                    ),
                ),
                (
                    "display_account_icon",
                    models.BooleanField(
                        default=True, help_text="Afficher l'icône du compte"
                    ),
                ),
                (
                    "display_cart_icon",
                    models.BooleanField(
                        default=True, help_text="Afficher l'icône du panier"
                    ),
                ),
                (
                    "display_cta_button",
                    models.BooleanField(
                        default=False, help_text="Afficher un bouton CTA"
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(
                        blank=True, help_text="Texte du bouton CTA", max_length=50
                    ),
                ),
                (
                    "cta_button_url",
                    models.URLField(blank=True, help_text="Lien pour le bouton CTA"),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False,
                        help_text="Ouvrir le lien du bouton CTA dans un nouvel onglet",
                    ),
                ),
                (
                    "selected_menu",
                    models.ForeignKey(
                        blank=True,
                        help_text="Menu à afficher dans le Header",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="layout.navigationmenu",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
