# Generated by Django 5.0.9 on 2024-11-18 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_about_section",
                    models.BooleanField(
                        default=True, help_text="Afficher la section 'À propos'"
                    ),
                ),
                (
                    "display_logo",
                    models.BooleanField(
                        default=True, help_text="Afficher le logo dans le Header"
                    ),
                ),
                (
                    "display_opening_hours",
                    models.BooleanField(
                        default=True, help_text="Afficher les horaires d'ouverture"
                    ),
                ),
                (
                    "selected_menu_1",
                    models.ForeignKey(
                        blank=True,
                        help_text="Premier menu à afficher dans le Footer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="layout.navigationmenu",
                    ),
                ),
                (
                    "selected_menu_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Second menu à afficher dans le Footer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="layout.navigationmenu",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
