# Generated by Django 5.0.9 on 2025-01-09 14:36

import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import wagtail.admin.viewsets.model
import wagtail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expeditions", "0001_initial"),
        ("product", "0001_initial"),
        ("taxes", "0002_taxmatrice_taxproduct_taxuser_delete_tax_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="locked"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="locked at"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Nom du client"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("JPY", "JPY"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "currency_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse de facturation"
                    ),
                ),
                (
                    "local_total_ht",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "local_total_tva",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "local_total_ttc",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "foreign_total_ht",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "foreign_total_tva",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "foreign_total_ttc",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("confirmed", "Confirmée"),
                            ("processing", "En traitement"),
                            ("proceed", "Traitée"),
                            ("shipped", "Expédiée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_invoiced",
                    models.BooleanField(default=False, verbose_name="Facturée"),
                ),
                ("is_payed", models.BooleanField(default=False, verbose_name="Payée")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="locked by",
                    ),
                ),
                (
                    "shipping_address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order",
                        to="expeditions.shippingaddress",
                    ),
                ),
                (
                    "shipping_label",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order",
                        to="expeditions.shippinglabel",
                    ),
                ),
                (
                    "shipping_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="expeditions.shippingoption",
                        verbose_name="Option d'expédition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="locked"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="locked at"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price_ht", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_price_ttc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="locked by",
                    ),
                ),
                (
                    "order",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_lines",
                        to="product.productpage",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxes.taxmatrice",
                    ),
                ),
                (
                    "variant_option",
                    models.ManyToManyField(blank=True, to="product.variantoption"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrderViewSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="locked"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="locked at"
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="locked by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                wagtail.models.PreviewableMixin,
                wagtail.admin.viewsets.model.ModelViewSet,
            ),
        ),
    ]
