# Generated by Django 5.0.9 on 2025-01-09 15:02

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devises", "0003_alter_currency_options"),
        ("orders", "0004_rename_order_orderline_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default=orders.models.get_default_currency,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="devises.currency",
                verbose_name="Devise",
            ),
        ),
    ]
