# Generated by Django 5.0.9 on 2025-01-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderline",
            old_name="Order",
            new_name="order",
        ),
    ]
